import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    width: '85%',
    height: 181,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    paddingTop: 35,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: '#000000',
  },
  title: {
    fontFamily: 'ABeeZee',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: -0.43,
    marginBottom: 5,
    textAlign: 'left',
    color: '#02113C',
  },
  message: {
    fontFamily: 'ABeeZee',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 15,
    lineHeight: 20,
    letterSpacing: -0.23,
    color: '#4E5876',
    marginBottom: 35,
    textAlign: 'left',
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cancelBtn: {
    width: '48%',
    height: 44,
    backgroundColor: '#DADADA',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#00000080',
    justifyContent: 'center',
    alignItems: 'center',
  },

  cancelText: {
    fontFamily: 'ABeeZee',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 15,
    lineHeight: 20,
    letterSpacing: -0.23,
    color: '#4E5876',
  },
  confirmBtn: {
    width: '48%',
    height: 44,
    backgroundColor: '#E9404B',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#00000080',
    justifyContent: 'center',
    alignItems: 'center',
  },

  confirmText: {
    fontFamily: 'ABeeZee',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 15,
    lineHeight: 20,
    letterSpacing: -0.23,
    color: '#FFFFFF',
  },
});
